/*
 * Weather Forecast API
 *
 * Weather Forecast
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Units of values
type HourlyUnits struct {
	Time             string `json:"time,omitempty"`
	Temperature2m    string `json:"temperature_2m,omitempty"`
	Showers          string `json:"showers,omitempty"`
	SurfacePressure  string `json:"surface_pressure,omitempty"`
	Windspeed10m     string `json:"windspeed_10m,omitempty"`
	Winddirection10m string `json:"winddirection_10m,omitempty"`
}
