version: '3.8'
services:

###############################
# DEFINITION OF INFRASTRUCTURE
# List of exposed ports: [5672, 15672]
###############################
  corr-rabbitmq:
    image: rabbitmq:latest
    build: ./dockerfiles/rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

###############################
# DEFINITION OF SERVICES
# List of exposed ports: []
###############################
  weather-acceptor:
    image: weather-acceptor
    build:
      context: ../../
      dockerfile: weather/weather-acceptor/Dockerfile
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      LOGLEVEL: ${LOGLEVEL}
    depends_on: 
      - corr-rabbitmq
    restart: unless-stopped

  weather-processor:
    image: weather-processor
    build:
      context: ../../
      dockerfile: weather/weather-processor/Dockerfile
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      LOGLEVEL: ${LOGLEVEL}
    depends_on: 
      - corr-rabbitmq
    restart: unless-stopped

###############################
# DEFINITION OF DATABASES
# List of exposed ports: [5434]
###############################

  weather-processor-db:
    image: postgres:11
    ports: 
      - "5434:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "weather_processor"
      TZ: "UTC"
    volumes:
      - ../../weather/weather-processor/database/postgres:/docker-entrypoint-initdb.d
networks:
  default:
    name: message-network