version: '3.8'
services:

###############################
# DEFINITION OF INFRASTRUCTURE
# List of exposed ports: [2181, 5672, 9092, 15672, 29092]
###############################
  corr-rabbitmq:
    image: rabbitmq:latest
    build: ./dockerfiles/rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"

  zookeeper:
    image: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "weather:1:1"
      KAFKA_ADVERTISED_HOST_NAME: REPLACE_WITH_WSL_IP
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://REPLACE_WITH_WSL_IP:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT      
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    restart: unless-stopped

###############################
# DEFINITION OF SERVICES
# List of exposed ports: []
###############################
  weather-acceptor:
    image: weather-acceptor
    build:
      context: ../../
      dockerfile: weather/weather-acceptor/Dockerfile
    environment:
      ENVIRONMENT: local
      LOGLEVEL: debug
    depends_on: 
      - corr-rabbitmq
    restart: unless-stopped

  weather-processor:
    image: weather-processor
    build:
      context: ../../
      dockerfile: weather/weather-processor/Dockerfile
    environment:
      ENVIRONMENT: local
      LOGLEVEL: debug
    depends_on: 
      - corr-rabbitmq
    restart: unless-stopped

###############################
# DEFINITION OF DATABASES
# List of exposed ports: [5434]
###############################

  weather-processor-db:
    image: postgres:11
    ports: 
      - "5434:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "weather_processor"
      TZ: "UTC"
    volumes:
      - ../../weather/weather-processor/database/postgres:/docker-entrypoint-initdb.d
networks:
  default:
    name: message-network