broker_connections:
  message_broker_type: kafka
  sending_topics:
    rabbitmq_broker:
      - name: weather
        connection_string: amqp://guest:guest@corr-rabbitmq:5672
    kafka_broker:
      - name: weather
        brokers: 
        - 172.25.252.229:29092
